Use tick-cluster from ringpop-common in tests

diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -11,9 +11,9 @@ set -e
 declare cram_opts="-v --shell=/bin/bash"
 declare package_dir="${0%/*}/../"
 declare prog_cram="cram"
-#declare prog_tick_cluster="${package_dir}/node_modules/ringpop/scripts/tick-cluster.js"
-declare prog_tick_cluster="${0%/*}/tick-cluster.js"
-declare prog_ringpop="node_modules/ringpop/main.js"
+declare ringpop_common_dir="${0%/*}/ringpop-common"
+declare ringpop_common_branch="tr-tick-cluster"
+declare prog_tick_cluster="${ringpop_common_dir}/tools/tick-cluster.js"
 declare pid_tickcluster=
 declare test_files="${0%/*}/*.t"
 declare isolated_test_files="${0%/*}/isolated/*.t"
@@ -46,6 +46,28 @@ _normalise_path() {
     else
         echo $path
         return 0
+    fi
+}
+
+#
+# Echos and runs the specified command.
+#
+run() {
+    echo "+ $@" >&2
+    "$@"
+}
+
+#
+# Clones or updates the ringpop-common repository.
+#
+fetch-ringpop-common() {
+    if [ ! -e "$ringpop_common_dir" ]; then
+        run git clone --depth=1 https://github.com/uber/ringpop-common.git "$ringpop_common_dir" --branch "$ringpop_common_branch"
+    else
+        run cd "$ringpop_common_dir"
+        run git fetch origin "$ringpop_common_branch"
+        run git checkout "FETCH_HEAD"
+        run cd - >/dev/null
     fi
 }
 
@@ -91,8 +113,11 @@ if [ ! -d "$package_dir/node_modules" ]; then
 fi
 
 if [ ! -x "$prog_tick_cluster" ]; then
-    echo "ERROR: Cannot find tick-cluster at: $prog_tick_cluster (or is not executable)" >&2
-    exit 1
+    fetch-ringpop-common 2>&1
+    if [ ! -x "$prog_tick_cluster" ]; then
+      echo "ERROR: Cannot find tick-cluster at: $prog_tick_cluster (or is not executable)" >&2
+      exit 1
+    fi
 fi
 
 # Clean up tick-cluster on exit
